### ISSUE TITLE
W3 Validation

### ISSUE THREAD

**Issue by dreneuw** [asc-csa/AlouetteApp#10]
A couple of issue were encountered when running the Scisat page into the W3 validator as an html file.

- There are multiple errors caused by spaces in links as such. These issues do not come from the python file, meaning they are generated by Dash Plotly:
![image](https://user-images.githubusercontent.com/56747050/107804513-f3709980-6d31-11eb-95ed-16dc2d3943f4.png)

- There are a couple color issues coming from the CSS:
![image](https://user-images.githubusercontent.com/56747050/107804557-fff4f200-6d31-11eb-987c-665b45de84f7.png)

- There are a couple of elements which apparently should not be descendant of the 'a' html element:
![image](https://user-images.githubusercontent.com/56747050/107804620-156a1c00-6d32-11eb-8e3c-67bbb2a5dbfa.png)

- The "ground_station", "x_axis_selection", "stat_selection" and etc. ids apparently have duplicates, not inside the python code:
![image](https://user-images.githubusercontent.com/56747050/107804687-30d52700-6d32-11eb-8f0e-d986ea671f03.png)
![image](https://user-images.githubusercontent.com/56747050/107804802-6a0d9700-6d32-11eb-89c9-0e2e5124f2ee.png)
![image](https://user-images.githubusercontent.com/56747050/107804930-99240880-6d32-11eb-94cd-71bbbb36bc0a.png)

- There is also an issue with a couple of attributes (persistence_* and persisted_*) that are apparently not allowed. An example:
![image](https://user-images.githubusercontent.com/56747050/107804727-40ed0680-6d32-11eb-8a24-62f7bdfb0fbb.png)

- Among other errors, there are canvas sizes error (not allowed values for width) and path elements missing a 'd' attribute:
![image](https://user-images.githubusercontent.com/56747050/107803831-21a1a980-6d31-11eb-867c-3903ba5e9666.png)
![image](https://user-images.githubusercontent.com/56747050/107803847-2b2b1180-6d31-11eb-845c-9db6ea03a185.png)

A lot of issues seem to be generated by Dash Plotly

**Comment by coleweusthem** [comment]
I'm going to split each of these into a separate issue and close this issue

**Comment by coleweusthem** [comment]
These have been separated into individual issues. Closing this larger issue.
