### ISSUE TITLE
Title and learn more button missing in French

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#107]
@coleweusthem 
![image](https://user-images.githubusercontent.com/11013061/116291638-d1988780-a762-11eb-935d-1e69c8cbdf47.png)

English version for context

![image](https://user-images.githubusercontent.com/11013061/116291745-effe8300-a762-11eb-83b1-faa5dbfbfee8.png)

**Comment by coleweusthem** [comment]
weird, looking into it

**Comment by nfee006** [comment]
@coleweusthem and now I'm noticing that most of the translation is broken too. It might be a config issue on my side but I haven't changed anything. 

config.py
![image](https://user-images.githubusercontent.com/11013061/116301558-2beb1580-a76e-11eb-9a2a-4d765ea859b1.png)

App-Launcher run.py
![image](https://user-images.githubusercontent.com/11013061/116301667-4ae9a780-a76e-11eb-835e-576f88eb7e0e.png)

**Comment by coleweusthem** [comment]
<img width="1196" alt="Screen Shot 2021-04-28 at 9 25 07 AM" src="https://user-images.githubusercontent.com/46227765/116403163-a154f580-a803-11eb-9fe7-b1c2f2fdc5c3.png">

I'm not sure what you're doing different, but mine is all in french.

**Comment by coleweusthem** [comment]
@nfee006, can you try the bug fix branch, looks like the APP_PREFIX was being ignored

**Comment by nfee006** [comment]
Fixed.
