### ISSUE TITLE
Needs a translation

### ISSUE THREAD

**Issue by coleweusthem** [asc-csa/AlouetteApp#112]
I'm going to list the translations needed here

**Comment by coleweusthem** [comment]
"Invalid values provided. Longitude values must be between -180 and 180. "
"Minimum values must be smaller than maximum values. All values must be "
"round numbers that are multiples of 5."

**Comment by coleweusthem** [comment]
"Invalid values provided. Latitude values must be between -90 and 90. "
"Minimum values must be smaller than maximum values. All values must be "
"round numbers that are multiples of 5."

**Comment by coleweusthem** [comment]
The form could not be submitted because errors were found.

**Comment by nfee006** [comment]
> "Invalid values provided. Longitude values must be between -180 and 180. "
> "Minimum values must be smaller than maximum values. All values must be "
> "round numbers that are multiples of 5."

"Valeurs non valides fournies. Les valeurs de longitude doivent être comprises entre -180 et 180. "
"Les valeurs minimales doivent être inférieures aux valeurs maximales. Toutes les valeurs doivent être "
"des nombres ronds qui sont des multiples de 5."

**Comment by nfee006** [comment]
> "Invalid values provided. Latitude values must be between -90 and 90. "
> "Minimum values must be smaller than maximum values. All values must be "
> "round numbers that are multiples of 5."

"Valeurs non valides fournies. Les valeurs de latitude doivent être comprises entre -90 et 90. "
"Les valeurs minimales doivent être inférieures aux valeurs maximales. Toutes les valeurs doivent être "
"des nombres ronds qui sont des multiples de 5."

**Comment by nfee006** [comment]
> The form could not be submitted because errors were found.

Le formulaire n'a pu être soumis car des erreurs ont été trouvées.

FYI, reference for the form validator: https://wet-boew.github.io/v4.0-ci/demos/formvalid/formvalid-fr.html
![image](https://user-images.githubusercontent.com/11013061/116607609-36d5af80-a900-11eb-81c7-732822ae4714.png)

**Comment by emilinecsa** [comment]
On June2, 2023, this bug seems to be fixed. Translations are good in the French version.
