### ISSUE TITLE
Web standards - CSS perspective issue 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#131]
Error in the CSS for the perspective property. (only 0 can be a unit. You must put a unit after your number.)
[40]
-webkit-perspective: 1000;
perspective: 1000;

**Comment by coleweusthem** [comment]
I'll wait on an answer about where this is coming from in scisat

**Comment by emilinecsa** [comment]
The latest version of the Alouette micro applications was deployed on the production server on April 13th. This new version includes the new header as requested by Communications. So, this issue might be fixed already. We need to doube-check.
