### ISSUE TITLE
Web standards - set charset (Comms 3) 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#132]
Move this line to immediately after the <head> (before the custom CSS)
[41]
`<meta charset="UTF-8">`

**Comment by coleweusthem** [comment]
It's all handled by dash, dash decided it goes second. So I hardcoded it in before the meta fields. This should work, but a side effect is that it's in the <head> twice now.

**Comment by emilinecsa** [comment]
This issue is fixed. The latest version of the Alouette micro applications was deployed on the production server on April 13th.
