### ISSUE TITLE
New footer

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#139]
As of March 7, 2023, the global (site-wide) footer at the bottom of each webpage, will now contain up to three bands:

The contextual band (optional) to provide support links specific to an entire group of pages, such as contact details for a program.
The main band to provide links to the GC contact page, the department and agency directory, the about government page and all theme pages.
The sub-footer band to provide a series of corporate links and the Canada wordmark.
No need for the contextual band - it doesn't make sense for our use case. We will need the main band and the sub-footer band.

The following file will need to be modified: https://github.com/asc-csa/AlouetteApp/blob/master/header_footer.py

Digging for the template for the new footer on the GC web site. Stand by.

**Comment by emilinecsa** [comment]
I updated and tested the page footer on my virtual machine. I works fine for both French and English languages, Finally, I committed the new HTML file to GitHub. We still need to deploy the new HTML file on both QA and production servers.
