### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#141]
![image](https://user-images.githubusercontent.com/11013061/225710840-1a32693d-93cc-4d81-bb44-68d209eb74af.png)

@emilinecsa is this something that you might have time to do, since you're already going in and changing the footers? Let me know if not.

**Comment by emilinecsa** [comment]
Sure. I can do it.

**Comment by emilinecsa** [comment]
The logo was removed from the application as requested by Communications. The latest version of the Alouette micro applications was deployed on the production server on April 13th.
