### ISSUE TITLE
Map selection has no impact on charts 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#6]
Charts do not auto-update when a station is selected on the map. 

![image](https://user-images.githubusercontent.com/11013061/103918127-6310ba80-50dc-11eb-8536-7606974cbd2b.png)

**Comment by nfee006** [comment]
Feature not bug

**Comment by emilinecsa** [comment]
This issue is not fixed. Both charts and the number of ionograms selected are now updated when the user filters for a specific station. I committed changes to GitHub and deployed the latest version on the QA server.
