### ISSUE TITLE
Broken links to GCWeb theming elements 

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#61]
A recent GCWeb update has broken the links to various external theming files (CSS, js, icons, etc..). More details here: https://github.com/wet-boew/GCWeb/issues/1792#issuecomment-797027224

![image](https://user-images.githubusercontent.com/11013061/110853111-35cdbd80-8281-11eb-911c-aa985e8e60d6.png)
![image](https://user-images.githubusercontent.com/11013061/110853141-3e25f880-8281-11eb-901a-3cc2565790b4.png)

From now on, we should aim to store all of these files locally.

**Comment by nfee006** [comment]
FYI @coleweusthem : seems it is a known issue. Someone on our side has recommended that take the files from https://github.com/wet-boew/GCWeb/releases/tag/v9.1.0 and store them locally.

**Comment by coleweusthem** [comment]
Thanks @nfee006, let me know if you would like me to work on it.

**Comment by nfee006** [comment]
@coleweusthem Yes please, if you think you can accomplish it in the short term. Otherwise I will just correct the links in the existing header/footers tomorrow and you can switch it out properly when you address the other header/footer conformity issues  https://github.com/asc-csa/AlouetteApp/issues/54 and https://github.com/asc-csa/AlouetteApp/issues/30.

**Comment by coleweusthem** [comment]
I'm looking into it/trying it now

**Comment by nfee006** [comment]
If you need any pointers for the translation (since the template only seems to be available in English), we're using the bootstrap3 static-header-footer in CKAN. Careful though since we've made some edits (language switch link, breadcrumbs, added the {{_(text)}} formatting for babel, and I removed some tags (https://github.com/asc-csa/ckanext-asc-csa/commit/7825127cf22c7965fe7c70959e4cc18dd793462a#diff-620b02671614f9a98f33d5746bcefe6e1f78696ba3513ab50465502097030435).   

https://github.com/asc-csa/ckanext-asc-csa/blob/master/ckanext/csa/templates/header.html
https://github.com/asc-csa/ckanext-asc-csa/blob/master/ckanext/csa/templates/footer.html

Would recommend looking at the history if you want a full list of the changes. Let me know if you have any questions and thanks again!

**Comment by coleweusthem** [comment]
@nfee006, I'm running into an issue with using the new theme locally. It seems like the 1k+ files within the 'GCWeb' and 'wet-boew' directories are causing plotly to become unresponsive. When I put them into the assets folder the page won't load, even if I haven't tried to include them anywhere. I think rather than allowing the 'assets' folder to be public facing it is trying to deliver all the files itself. Do you know if there is a CDN we can reliably use?

**Comment by nfee006** [comment]
I'm not sure but I can ask around. Is this useful/something we could implement? https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html

I found some additional info here that might be useful: 

https://wet-boew.github.io/themes-dist/GCWeb/gcweb-theme/implementing.html
"Menu CDN
Principal publisher update those following HTML fragment file every time there is a change to Canada.ca top menu.

English: https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-en.html
French: https://www.canada.ca/content/dam/canada/sitemenu/sitemenu-v2-fr.html"

**Comment by coleweusthem** [comment]
That could be helpful. thanks I'll try it out

**Comment by coleweusthem** [comment]
@nfee006 does: '4 - GCWeb / run - Default - Target: You want to implement the Canada.ca theme with the default header/footer and you want to always be up to date with the latest WET and Canada.ca changes.' sound good to you? to my understanding automatically getting the theme updates and header/footer changes would be ideal. But it may be a little more work in the short term. 

The other option would be '2 - GCWeb / version - Default - Target: You want to implement the Canada.ca theme with the default header/footer and you want to test any new changes that are released.' you would need to maintain the changes making it more work to maintain, but we wouldn't need to implement the code to automatically pull the header and footer. And if you expect any issues arising from the header/footer changing you'd be able to test new changes before releasing them.

Do you have a preference?

**Comment by nfee006** [comment]
I like option 2 because CSS changes have a tendency to mess up our layout. I'd prefer being able to test things out before deployment. 

When you say more work to maintain, how much additional work would you imagine?

**Comment by coleweusthem** [comment]
@nfee006 just every time there is a release that needs to be implemented you would need to test it and deploy it. Not too much at any given time, maybe an hour or so. But depending the frequency of changes you need to implement could become a fairly regular task.

**Comment by nfee006** [comment]
I'm going to confirm that this is acceptable. I'll get back to you ASAP (max 1hr).

**Comment by nfee006** [comment]
I've just noticed this 
![image](https://user-images.githubusercontent.com/11013061/110964686-71b85f80-8321-11eb-81e1-54cae3c2c944.png)
from here https://github.com/wet-boew/GCWeb/releases/tag/v9.1.0

Is this what you were initially looking for?

**Comment by coleweusthem** [comment]
@nfee006 I saw that but there didn't seem to be any documentation on how to use it. I'll play with it a bit and see if it does what I need. Hopefully I just need to include the main theme javascript and main theme css

**Comment by coleweusthem** [comment]
That seems to have worked. I'll test it a bit more to make sure and if you'd like I can see about auto updating the menu automatically from those links you sent.

<img width="1838" alt="Screen Shot 2021-03-12 at 12 12 40 PM" src="https://user-images.githubusercontent.com/46227765/110966968-40915c80-832c-11eb-927c-83747b91c05e.png">

**Comment by nfee006** [comment]
Great! To confirm: did you switch out the header and footer for the static-header-footer from the GCWeb theme? I'm 99% sure that the existing header/footers were actually copy-pasted from a live government of Canada site rather than using the approved template (and that's part of the reason that they're creating so many conformity issues). I think your screenshot must be using the old header because there isn't a link at the top to switch the language.

Like this 
![image](https://user-images.githubusercontent.com/11013061/110969239-716e9300-8326-11eb-8466-9ea067f7a2a4.png)

from https://github.com/asc-csa/AlouetteApp/issues/30, https://github.com/asc-csa/AlouetteApp/issues/54

**Comment by nfee006** [comment]
Reference: https://github.com/wet-boew/GCWeb/tree/db8f99ce9d1f8f58a58771269fa18d0b5c995a8a/site/pages/gcweb-theme/static-header-footer

**Comment by coleweusthem** [comment]
@nfee006 yeah the header is copy and pasted in. Would you like me to redo it with the new header? or is there another way you'd like it implemented

**Comment by nfee006** [comment]
Yes please, from https://github.com/wet-boew/GCWeb/tree/db8f99ce9d1f8f58a58771269fa18d0b5c995a8a/site/pages/gcweb-theme/static-header-footer unless you know of another source.

**Comment by coleweusthem** [comment]
@nfee006, is there a french version? I can't seem to find it. Also all the links to assets in it are broken.

**Comment by coleweusthem** [comment]
@nfee006, is there a french version? I can't seem to find it, also I'm using bootstrap-4.html as it seems to have working asset links, however it is labeled 'experimental' so let me know if you think that is a problem

**Comment by coleweusthem** [comment]
I may need to put this on hold for the moment. As you can see in the screenshot the theme from bootstrap-4.html seems to be incorrect as the 'experimental' description implied it may be. And the other file (bootstrap-3.html) is looking for assets in the location we can no longer pull assets from. I could go through and manually implement them if you would like, but I'm getting the feeling we may be using the wrong files as reference. I would expect the latest version of the theme to have correct links embedded.

<img width="1837" alt="Screen Shot 2021-03-15 at 10 45 25 AM" src="https://user-images.githubusercontent.com/46227765/111163091-8e4fd400-857b-11eb-9c6a-1c080ad74897.png">

**Comment by nfee006** [comment]
If you need to wait until later in the process before implementing the correct header and footer, that's fine. We do need a fix for production ASAP though - even if it isn't the correct/conform header/footer template. Also, I would caution you against trying to fix HTML issues in the existing header/footer since we absolutely need an approved GoC header/footer for conformity. 

This is what production currently looks like. 

![image](https://user-images.githubusercontent.com/11013061/111164886-d61f2d00-8574-11eb-8af9-47d373848ebd.png)

**Comment by coleweusthem** [comment]
@nfee006, I have a fix on my local machine. I'll fix the couple broken images and push it

**Comment by nfee006** [comment]
We'll need to the same for SCISAT as well please. Thanks.

**Comment by nfee006** [comment]
Temporarily addressed by https://github.com/asc-csa/AlouetteApp/commit/05af38f4eddb2cd877fb806c6bcd0469bed7c58f. We still require an approved GoC header for conformity.

**Comment by coleweusthem** [comment]
@nfee006, I realized that I need an english and french version. Do you think it would be safe to take from here? https://wet-boew.github.io/themes-dist/GCWeb/gcweb-theme/index.html

**Comment by nfee006** [comment]
I'm not aware of a French version - do you see one on that page? That is supposed to be an official/reliable page. There's always the files from the menu CDN for some of it. 

English: https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-v5-en.html
French: https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-v5-fr.html

I had to use Babel to translate the one in CKAN (NB. the CKAN header has been edited manually - you can see in the commits). https://github.com/asc-csa/ckanext-asc-csa/blob/master/ckanext/csa/templates/header.html https://github.com/asc-csa/ckanext-asc-csa/blob/master/ckanext/csa/templates/footer.html

**Comment by coleweusthem** [comment]
@nfee006, I can do the translation manually if need be, but I still am lacking the translations. I need a reliable source for what they need to be. So what can I use as a reference?

**Comment by emilinecsa** [comment]
I fixed the translation and successfully compiled the PO file. Communications approved. I committed changes to GitHub and deployed the latest version on the QA server.
