### ISSUE TITLE
 Visit our Github page to learn more about the code used to make this application.

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/AlouetteApp#62]
replace with
Visit our Github page to learn more about the code [used to make this application](https://github.com/asc-csa/AlouetteApp) and the [code used to extract metadata and parameters from the ionogram images](https://github.com/asc-csa/Alouette_extract)

**Comment by nfee006** [comment]
Addressed by https://github.com/asc-csa/AlouetteApp/commit/53b92a52f0021336128ece3e3e1e3675b681f7fa
