### ISSUE TITLE
Please note that the extracted ionogram parameters, such as max depth and min frequency, are provided primarily for demonstration purposes.

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/AlouetteApp#63]
Replace with
Please note that the metadata and parameters extracted ionogram ([see more about the extraction process](https://github.com/asc-csa/Alouette_extract)) are provided primarily for demonstration purposes.

**Comment by nfee006** [comment]
Addressed by https://github.com/asc-csa/AlouetteApp/commit/53b92a52f0021336128ece3e3e1e3675b681f7fa
