### ISSUE TITLE
AttributeError: module 'dash_core_components' has no attribute 'Store'

### ISSUE THREAD

**Issue by nfee006** [asc-csa/AlouetteApp#97]
This happened after I installed the new dash_core_components fork and ran python run.py (or python3 run.py) in App-Launcher. My alouette repo is up to date with Development. 

Does this ring a bell @coleweusthem?

![image](https://user-images.githubusercontent.com/11013061/115030160-c9a03400-9e94-11eb-881b-780fb6d4309f.png)

If this is actually related to my installation process for dash_core_components, it was: 

1. Navigate to the python3.8/sites-packages folder for my venv.
2. git clone https://github.com/coleweusthem/dash-core-components
3. cd dash-core-components
4. python3 setup.py install

I tried a few fancier approaches (simlink etc...) but they created issues.

**Comment by coleweusthem** [comment]
You may need to go into dash-core-components, run 'npm install' and 'npm run build’. I used nvm to manage my node version and was using node v14. You may also want to pull the latest version, of my dash-core-components fork, I just pushed a change that pulls in my custom plotly.js.

I don’t think I ever used the setup.py, but that may have been part of npm run build

Let me know if that helps.

**Comment by coleweusthem** [comment]
@nfee006, let me know if you'd rather not install node js and I'll try pushing what I have for distribution files, as I haven't done that yet. I was building them instead.

**Comment by coleweusthem** [comment]
You can also check it worked by looking in the console for the message 'loaded custom plotly js' I added that as a simple indicator to quickly see if we are running our custom version or not

**Comment by nfee006** [comment]
Great - thanks @coleweusthem. I'll try that shortly.

**Comment by coleweusthem** [comment]
@nfee006, just realized you may need to make sure you are on the master branch, Looks like dev might be the default.

**Comment by nfee006** [comment]
Error was in the config on my side. Fixed.
